### PR TITLE
Add images for plugin "subtitle extract"

### PR DESCRIPTION
**Pull request by GolDNenex**
I've made a image for the plugin jellyfin/jellyfin-plugin-subtitleextract. This will fix this issue: https://github.com/jellyfin/jellyfin-plugin-subtitleextract/issues/11.

I don't know  how to optimize further the svg version (60kib).

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
It looks like the SVG is just has single bitmap embedded inside. We try to avoid that. The SVG should be the "source-of-truth" so we can easily regenerate the png files in different sizes if needed.

**Comment by GolDNenex** [comment]
Sorry i don't work with svg generally. I remade it based on `jellyfin-plugin-playbackreporting.svg` since i was already copying the style of it. Tell me if its good for you.

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
The text should be converted to a path so it will properly render the font. You can also export the SVG as "Optimized SVG" in Inkscape so it removes the editor information, resulting in a smaller file size.

**Comment by GolDNenex** [comment]
Converting the text to a path increase the svg from 2,9KiB to 7KiB. 

I've looked others svg for the plugins, some of them use a text and not a path. If it is also to be corrected, I can do what is necessary.

**Comment by nielsvanvelzen** [comment]
> Converting the text to a path increase the svg from 2,9KiB to 7KiB.

Yeah that's because it now contains the drawing instructions for the letters inline. It would be much bigger if you had to include the font file though

> I've looked others svg for the plugins, some of them use a text and not a path. If it is also to be corrected, I can do what is necessary.

While it might be nice to fix those it's not the biggest issue as the server doesn't actually use the svg versions (yet).

**Review by nielsvanvelzen — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Pull request merged**
