### PR TITLE
Logo, Colours & Artboard name standardization, add license, add CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by EraYaN**
Took the same source as #1 

~~Used the centered icon from that PR.~~ Used reconstructed, mathematically perfect icon. Stretched to square.
Made all icons 512x512 and banners 512x~~1500~~1536.
~~All offsets and sizes pixel perfect. (no half pixels)~~
~~Used same Chewy font.~~
Scaled the text down a little.
wrote the brand name without the uppercase J.

Created single master *.ai file with all artboards. All icons are linked symbols.

Also the `branding` folder is a direct export (single action) from Illustrator. Is very convenient to add other sizes and scaling (for android or iOS for example).

Art board names are: (we should standardize these, and these are not completely correct)

- banner-light
- ~~banner-light-mono~~
- banner-dark
- ~~banner-dark-mono~~
- icon-~~blue~~solid
- icon-transparent
- ~~icon-white-blue~
- ~~icon-white-transparent~~
- ~~icon-black-transparent~~

~~These need some work since they are not truly clear. I'm happy with the first parts, 'icon' and 'banner' are clear. For example `icon-blue` should probably be `icon-color-blue` to always have `jellyfin_{type}-{foreground}-{background}-{scaling}.{format}`~~

Proposed filename format: `jellyfin_{type}-{use_env}-@{scaling}.{format}`

### CODE REVIEW

**Comment by EraYaN** [comment]
We could use the dark blue as the solid color instead of the black. The white not sure though what to do about that.

I suppose the choice of Chewy font was intentionally "jelly" cause well, it's in the name.

I would even argue that the lopsidedness of the logo adds character.
Let me reconstruct it with proper guides.

**Comment by EraYaN** [comment]
Also a little bit of a fiddling with all the possible designs (and colors)

https://erayan.com/jellyfin-logo-colors.html

**Comment by anthonylavado** [comment]
screen shot 2019-01-02 at 12 34 48 am
Here's three fonts that I picked from Google Fonts. It's Open Sans, Source Sans Pro, and Quicksand, in that order.

**Comment by joshuaboniface** [comment]
I honestly love Quicksand + Bfayer's Monochrome logo icon with the default colour scheme. Also the lopsided XY stretch logo seems really cool, like it's 3d perspective rather than just lopsided.

**Comment by anthonylavado** [comment]
I do like Quicksand as well, and from the original file, I loooove the background from the original concept, where it is identified as "Rich Black" - #000B25. I realize that probably doesn't look good though.

As far as the logo design itself, I'm warming up to the fully symmetrical one.

**Comment by EraYaN** [comment]
I like Quicksand as well. Pretty readable even in small font. For Chewy I liked the lowercase J but I think for Quicksand the upper case is better.

And then with the baseline of the font aligned with the bottom on the inner blob. And the top of the e also aligned.

**Comment by bfayers** [comment]
+1 for Quicksand, looks great

**Comment by dkanada** [comment]
I wanted to mention here that I don't think we should use that shade of blue used in the background for anything. Dark themes look best with gray as the base and the app colors only used for accenting the gray in my opinion. Other than that, the current proposed icon and font look amazing.

**Comment by dkanada** [comment]
This [link](https://graphicdesign.stackexchange.com/questions/53227/inkscape-0-91-how-does-one-convert-symbols-to-a-path) might answer your question, symbols are Adobe specific stuff so we might want to clean up the svgs at some point to work across any svg editor. I use Inkscape a ton so I can make sure they are easy to edit once we decide on a final design.

**Comment by nvllsvm** [comment]
The `.ai` files should also be removed entirely as the SVGs should be the source of truth.

**Comment by dkanada** [comment]
One more thing to note, are the two colors in the current gradient the final selection?

`
#aa5cc3
#00a4dc
`

If so, do we use one of these for the main accent color in the app, and which one? I vote for the blue but purple would probably look fine as well.

**Comment by EraYaN** [comment]
If we are to use the SVG as a source of truth you will lose a lot of information going from something like a psd/ai to an SVG. Also the exporting or resizing will be a pain (not single click). Most importantly all the links, artboards and guides won't export nicely.

Anyhow I can add a master svg I suppose, not sure how to properly include all the artboards and layers though. Has anyone ever worked with layers in svgs?

I can't get inkscape to respect the font, nor to edit the path. ([example](https://matrix.to/#/!LCLiMJSFwJyNyVtqxj:matrix.org/$15466895382053901wgpvv:matrix.org?via=matrix.org&via=matrix.possumlodge.me&via=dkanada.com&via=half-shot.uk)) I want to convert down to outlines, but that will hurt editability. In the end this is the proper way, but if you still need to make SVG edits, it's not very nice.

**Comment by EraYaN** [comment]
Alright updated, what sizes do we need?

1x would be 512 pixels high.

**Comment by sparky8251** [comment]
I'd say one last addition should be the font.

Do something like `Fonts/<fontname>` and in there but the ttf and license file for said font. Just in case folks need it for whatever reason.

**Comment by EraYaN** [comment]
Should we really git version the font? I'd rather link away to google fonts.

**Comment by sparky8251** [comment]
Its a small file honestly. We wont be changing it often either. Never know if the font will be pulled from whatever site you link to either.

**Comment by nvllsvm** [comment]
I agree, adding the font would be a good idea.

**Comment by nvllsvm** [comment]
Separate PR for that please. I'm impatient and want to have these in the main repo :P

**Pull request merged**
