### PR TITLE
Added device images

### PR DESCRIPTION
**Pull request by sparky8251**
These are used on the web ui dashboard to indicate what type of device a particular instance is.

### CODE REVIEW

**Comment by LeoVerto** [comment]
Can we host all of these in this repo without licensing issues?

**Comment by sparky8251** [comment]
Unknown. Plan to open new issues on both UX and web after merge to get valid artwork for each image that conforms to the rules of each trademark holder.

This is just so we don't get screwed by having the artwork go missing on us in the meantime.

**Comment by EraYaN** [comment]
These should be bundled with the web UI as assets, otherwise they will not work when there is no internet connection.

**Comment by dkanada** [comment]
should be obsolete with jellyfin/jellyfin-web#379

**Pull request closed without merging**
