### PR TITLE
Add plugin images

### LINKED ISSUE #43: Add plugin images
* [x] Kodi Sync Queue 
* [x] CoverArtArchive
* [x] MusicBrainz
* [x] Fanart
* [x] OpenSubtitles
* [x] TMDB
* [x] Trakt
* [x] LDAP
* [x] TVDB
* [x] Next PVR
* [x] TV Maze
* [x] ~~TMDB Boxsets~~ (**Should be merged with TMDB**)
* [x] ~~Bookshelf~~ (**Should be split**)
  * [x] Google Books
  * [x] ComicVine
  * [x] EPUB
  * [x] Calibre 
* [x] Auto Organize
* [x] OMDB
* [x] Pushbullet
* [x] TV Headend
* [x] Kitsu
* [x] AniSearch
* [x] AniList
* [x] AniDB
* [x] Slack
* [x] ~~ServerWMC~~ (**Potentially discontinued**)
* [x] Email Notifications
* [x] Playback Reporting
* [x] Reports
* [x] Missing Episode Provider (**Not published**)

### PR DESCRIPTION
**Pull request by MrTimscampi**
Fixes #43 

[jellyfin-plugin-tmdb](https://github.com/jellyfin/jellyfin-plugin-tmdb)
jellyfin-plugin-tmdb
[jellyfin-plugin-kodisyncqueue](https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue)
jellyfin-plugin-kodisyncqueue
[jellyfin-plugin-coverartarchive](https://github.com/jellyfin/jellyfin-plugin-coverartarchive)
jellyfin-plugin-coverartarchive
[jellyfin-plugin-musicbrainz](https://github.com/jellyfin/jellyfin-plugin-musicbrainz)
jellyfin-plugin-musicbrainz
[jellyfin-plugin-trakt](https://github.com/jellyfin/jellyfin-plugin-trakt)
jellyfin-plugin-trakt
[jellyfin-plugin-slack](https://github.com/jellyfin/jellyfin-plugin-slack)
jellyfin-plugin-slack
[jellyfin-plugin-ldapauth](https://github.com/jellyfin/jellyfin-plugin-ldapauth)
jellyfin-plugin-ldapauth
[jellyfin-plugin-anilist](https://github.com/jellyfin/jellyfin-plugin-anilist)
jellyfin-plugin-anilist
[jellyfin-plugin-googlebooks](https://github.com/jellyfin/jellyfin-plugin-googlebooks)
jellyfin-plugin-googlebooks
[jellyfin-plugin-comicvine](https://github.com/jellyfin/jellyfin-plugin-comicvine)
jellyfin-plugin-comicvine
[jellyfin-plugin-calibre](https://github.com/jellyfin/jellyfin-plugin-calibre)
jellyfin-plugin-calibre
[jellyfin-plugin-epub](https://github.com/jellyfin/jellyfin-plugin-epub)
jellyfin-plugin-epub
[jellyfin-plugin-autoorganize](https://github.com/jellyfin/jellyfin-plugin-autoorganize)
jellyfin-plugin-autoorganize
[jellyfin-plugin-pushbullet](https://github.com/jellyfin/jellyfin-plugin-pushbullet)
jellyfin-plugin-pushbullet
[jellyfin-plugin-emailnotifications](https://github.com/jellyfin/jellyfin-plugin-emailnotifications)
jellyfin-plugin-emailnotifications
[jellyfin-plugin-opensubtitles](https://github.com/jellyfin/jellyfin-plugin-opensubtitles)
jellyfin-plugin-opensubtitles
[jellyfin-plugin-fanart](https://github.com/jellyfin/jellyfin-plugin-fanart)
jellyfin-plugin-fanart
[jellyfin-plugin-tvdb](https://github.com/jellyfin/jellyfin-plugin-tvdb)
jellyfin-plugin-tvdb
[jellyfin-plugin-omdb](https://github.com/jellyfin/jellyfin-plugin-omdb)
jellyfin-plugin-omdb
[jellyfin-plugin-tvheadend](https://github.com/jellyfin/jellyfin-plugin-tvheadend)
jellyfin-plugin-tvheadend
[jellyfin-plugin-anidb](https://github.com/jellyfin/jellyfin-plugin-anidb)
jellyfin-plugin-anidb
[jellyfin-plugin-nextpvr](https://github.com/jellyfin/jellyfin-plugin-nextpvr)
jellyfin-plugin-nextpvr
[jellyfin-plugin-kitsu](https://github.com/jellyfin/jellyfin-plugin-kitsu)
jellyfin-plugin-kitsu
[jellyfin-plugin-anisearch](https://github.com/jellyfin/jellyfin-plugin-anisearch)
jellyfin-plugin-anisearch
[jellyfin-plugin-playbackreporting](https://github.com/jellyfin/jellyfin-plugin-playbackreporting)
jellyfin-plugin-playbackreporting
[jellyfin-plugin-reports](https://github.com/jellyfin/jellyfin-plugin-reports)
jellyfin-plugin-reports
[jellyfin-plugin-tvmaze](https://github.com/jellyfin/jellyfin-plugin-tvmaze)
jellyfin-plugin-tvmaze

### CODE REVIEW

**Comment by MrTimscampi** [comment]
The AniSearch one is really ugly, but that's the best I was able to make in an hour based on their ugly logo and color scheme...

**Comment by oddstr13** [comment]
> The AniSearch one is really ugly, but that's the best I was able to make in an hour based on their ugly logo and color scheme...

I think it looks fine, except for the slight rotation of the logo.
I realize it is tilted like that in the website header, bit I think it looks a bit out-of-place in the card like that.
ComicVine is the only other logo which is tilted, and it looks far more natural to me (probably due to not having a straight line?)

They also have an alternative logo used in the rating button as seen here; https://www.anisearch.com/forum/thread/28504,api-support and they may be able to provide advice on the branding if contacted via their forums.

**Comment by MrTimscampi** [comment]
Note:

I have reached out to TV Maze to ask for a proper SVG of their logo, since we've had prior contact with them.  
They replied and should get back to me with a proper file in the next few days.

Consider the current image as temporary, as a result. I'll replace it once we get the file from them.

**Comment by dkanada** [comment]
The standard size you enforce across all icons starts to fall apart when oddly shaped logos exist like Cover Art Archive, which looks miniscule compared to the square icons. Google even has an entire section in their style guidelines about maintaining [visual consistency](https://material.io/design/iconography/system-icons.html) between different shapes.

**Review by anthonylavado — APPROVED** [review]

**Pull request merged**
